import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  // Luxury Design Styles for Case 2 (Handball Spezial)
  luxuryContainer: {
    flex: 1,
    backgroundColor: '#000',
  },
  heroSection: {
    height: height * 0.8,
    position: 'relative',
  },
  heroImage: {
    width: '100%',
    height: '100%',
  },
  heroOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  heroContent: {
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  heroSubtitle: {
    fontSize: 14,
    color: '#fff',
    letterSpacing: 3,
    marginBottom: 10,
    fontWeight: '300',
  },
  heroTitle: {
    fontSize: 48,
    color: '#fff',
    fontWeight: 'bold',
    textAlign: 'center',
    letterSpacing: 2,
    marginBottom: 20,
    lineHeight: 52,
  },
  heroTagline: {
    fontSize: 16,
    color: '#ccc',
    textAlign: 'center',
    fontStyle: 'italic',
    letterSpacing: 1,
  },
  storySection: {
    backgroundColor: '#fff',
    paddingHorizontal: 40,
    paddingVertical: 60,
  },
  storyHeader: {
    alignItems: 'center',
    marginBottom: 40,
  },
  storyTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#000',
    letterSpacing: 3,
    marginBottom: 20,
  },
  divider: {
    width: 60,
    height: 2,
    backgroundColor: '#000',
  },
  storyText: {
    fontSize: 18,
    lineHeight: 28,
    color: '#333',
    textAlign: 'center',
    fontWeight: '300',
    letterSpacing: 0.5,
  },
  featuresGrid: {
    backgroundColor: '#f8f8f8',
    paddingHorizontal: 40,
    paddingVertical: 60,
  },
  gridTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#000',
    letterSpacing: 3,
    textAlign: 'center',
    marginBottom: 50,
  },
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  featureCard: {
    width: '48%',
    backgroundColor: '#fff',
    padding: 30,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  featureNumber: {
    marginBottom: 15,
  },
  featureNumberText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#000',
    letterSpacing: 2,
  },
  featureText: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
    fontWeight: '400',
  },
  ctaSection: {
    backgroundColor: '#000',
    paddingHorizontal: 40,
    paddingVertical: 80,
    alignItems: 'center',
  },
  ctaTitle: {
    fontSize: 24,
    color: '#fff',
    fontWeight: 'bold',
    letterSpacing: 2,
    marginBottom: 40,
    textAlign: 'center',
  },
  ctaButton: {
    backgroundColor: '#fff',
    paddingHorizontal: 50,
    paddingVertical: 18,
    borderRadius: 0,
  },
  ctaButtonText: {
    fontSize: 16,
    color: '#000',
    fontWeight: 'bold',
    letterSpacing: 2,
  },
  footer: {
    backgroundColor: '#fff',
    paddingHorizontal: 40,
    paddingVertical: 40,
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  footerText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000',
    letterSpacing: 2,
    marginBottom: 8,
  },
  footerSubtext: {
    fontSize: 14,
    color: '#666',
    fontStyle: 'italic',
  },

  // Default Design Styles
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  bannerContainer: {
    position: 'relative',
  },
  headerImage: {
    width: '100%',
    height: 900,
  },
  bannerOverlay: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 10,
  },
  bannerTextBox: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    padding: 10,
    marginRight: 10,
  },
  bannerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#000',
  },
  bannerSubtitle: {
    fontSize: 16,
    color: '#666',
  },
  contentContainer: {
    padding: 20,
  },
  descriptionContainer: {
    marginBottom: 30,
  },
  descriptionTitle: {
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 10,
  },
  description: {
    fontSize: 16,
    lineHeight: 24,
    color: '#333',
  },
  featuresContainer: {
    marginBottom: 20,
  },
  featuresTitle: {
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 15,
  },
  featureItem: {
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 8,
    color: '#333',
  },

  // Nike-specific styles for IntroductionScreen3
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#000',
  },
  backButton: {
    padding: 4,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    letterSpacing: 2,
  },
  headerRight: {
    width: 32,
  },
  scrollContainer: {
    flex: 1,
  },
  nikeBannerOverlay: {
    position: 'absolute',
    bottom: 40,
    right: 20,
    alignItems: 'flex-end',
  },
  nikeBannerContent: {
    alignItems: 'flex-end',
  },
  nikeSlogan: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 8,
    letterSpacing: 2,
    textShadowColor: 'rgba(0, 0, 0, 0.7)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
  },
  nikeBannerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 6,
    textAlign: 'right',
    textShadowColor: 'rgba(0, 0, 0, 0.7)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  nikeBannerSubtitle: {
    fontSize: 16,
    color: '#fff',
    textAlign: 'right',
    fontStyle: 'italic',
    textShadowColor: 'rgba(0, 0, 0, 0.7)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  nikeStorySection: {
    backgroundColor: '#000',
    paddingHorizontal: 30,
    paddingVertical: 50,
  },
  nikeBrandHeader: {
    alignItems: 'center',
    marginBottom: 30,
  },
  nikeBrandTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#fff',
    letterSpacing: 3,
    marginBottom: 15,
    textAlign: 'center',
  },
  nikeDivider: {
    width: 80,
    height: 3,
    backgroundColor: '#fff',
  },
  nikeStoryText: {
    fontSize: 18,
    lineHeight: 28,
    color: '#ccc',
    textAlign: 'center',
    fontWeight: '300',
  },
  nikeCategoriesSection: {
    backgroundColor: '#f5f5f5',
    paddingHorizontal: 20,
    paddingVertical: 50,
  },
  nikeCategoriesTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#000',
    letterSpacing: 2,
    textAlign: 'center',
    marginBottom: 40,
  },
  nikeCategoriesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  nikeCategoryCard: {
    width: '48%',
    backgroundColor: '#fff',
    padding: 25,
    marginBottom: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  nikeCategoryIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#f0f0f0',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
  },
  nikeCategoryTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 8,
    textAlign: 'center',
  },
  nikeCategoryDesc: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    lineHeight: 20,
  },
  nikePerformanceSection: {
    backgroundColor: '#fff',
    paddingHorizontal: 20,
    paddingVertical: 50,
  },
  nikePerformanceTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#000',
    letterSpacing: 2,
    textAlign: 'center',
    marginBottom: 40,
  },
  nikeFeaturesGrid: {
    gap: 15,
  },
  nikeFeatureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8f8f8',
    padding: 20,
    borderRadius: 12,
  },
  nikeFeatureNumber: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  nikeFeatureNumberText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  nikeFeatureText: {
    flex: 1,
    fontSize: 16,
    color: '#333',
    fontWeight: '500',
  },
  nikeCTASection: {
    backgroundColor: '#000',
    paddingHorizontal: 30,
    paddingVertical: 60,
    alignItems: 'center',
  },
  nikeCTATitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#fff',
    letterSpacing: 2,
    marginBottom: 15,
    textAlign: 'center',
  },
  nikeCTASubtitle: {
    fontSize: 16,
    color: '#ccc',
    textAlign: 'center',
    marginBottom: 40,
    lineHeight: 24,
  },
  nikeCTAButtons: {
    width: '100%',
    gap: 15,
  },
  nikeShopButton: {
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    borderRadius: 8,
  },
  nikeShopButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000',
    letterSpacing: 1,
  },
  nikeShopIcon: {
    marginLeft: 10,
    color: '#000',
  },
  nikeExploreButton: {
    borderWidth: 2,
    borderColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    borderRadius: 8,
  },
  nikeExploreButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    letterSpacing: 1,
  },
  nikeValuesSection: {
    backgroundColor: '#f5f5f5',
    paddingHorizontal: 20,
    paddingVertical: 50,
  },
  nikeValuesTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#000',
    letterSpacing: 2,
    textAlign: 'center',
    marginBottom: 40,
  },
  nikeValuesContent: {
    gap: 30,
  },
  nikeValueItem: {
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  nikeValueTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#000',
    marginTop: 15,
    marginBottom: 10,
    textAlign: 'center',
  },
  nikeValueDesc: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    lineHeight: 24,
  },
});

export default styles; 